import {
  DollarSign, TrendingUp, Calendar, Zap, AlertTriangle,
  Activity, PieChart as PieChartIcon, BarChart2, Cloud, Server,
} from 'lucide-react'

export const WIDGET_REGISTRY = [
  {
    id: 'kpi-total-spend',
    name: 'Total Spend',
    description: 'Current month total cloud spend across all providers',
    category: 'Key Metrics',
    icon: DollarSign,
    color: '#F59E0B',
    defaultW: 3, defaultH: 3,
    minW: 2, minH: 3,
  },
  {
    id: 'kpi-vs-last-month',
    name: 'Month-over-Month',
    description: 'Spend delta compared to the previous month',
    category: 'Key Metrics',
    icon: TrendingUp,
    color: '#F43F5E',
    defaultW: 3, defaultH: 3,
    minW: 2, minH: 3,
  },
  {
    id: 'kpi-forecast',
    name: 'Month-End Forecast',
    description: 'Projected total spend by end of month vs budget',
    category: 'Key Metrics',
    icon: Calendar,
    color: '#F59E0B',
    defaultW: 3, defaultH: 3,
    minW: 2, minH: 3,
  },
  {
    id: 'kpi-savings',
    name: 'Savings Identified',
    description: 'Potential monthly savings available in Optimizer',
    category: 'Key Metrics',
    icon: Zap,
    color: '#10B981',
    defaultW: 3, defaultH: 3,
    minW: 2, minH: 3,
  },
  {
    id: 'provider-aws',
    name: 'AWS Spend',
    description: 'Amazon Web Services cloud usage and spend',
    category: 'Cloud Providers',
    icon: Cloud,
    color: '#FF9900',
    defaultW: 4, defaultH: 3,
    minW: 3, minH: 3,
  },
  {
    id: 'provider-gcp',
    name: 'Google Cloud Spend',
    description: 'Google Cloud Platform usage and spend',
    category: 'Cloud Providers',
    icon: Cloud,
    color: '#4285F4',
    defaultW: 4, defaultH: 3,
    minW: 3, minH: 3,
  },
  {
    id: 'provider-azure',
    name: 'Azure Spend',
    description: 'Microsoft Azure usage and spend',
    category: 'Cloud Providers',
    icon: Cloud,
    color: '#0078D4',
    defaultW: 4, defaultH: 3,
    minW: 3, minH: 3,
  },
  {
    id: 'chart-area-spend',
    name: 'Spend Trend',
    description: 'Daily cloud spend over time, stacked by provider',
    category: 'Charts',
    icon: Activity,
    color: '#3B82F6',
    defaultW: 12, defaultH: 5,
    minW: 6, minH: 4,
  },
  {
    id: 'chart-donut',
    name: 'Cost by Service',
    description: 'Spend allocation across your top cloud services',
    category: 'Charts',
    icon: PieChartIcon,
    color: '#8B5CF6',
    defaultW: 6, defaultH: 5,
    minW: 4, minH: 4,
  },
  {
    id: 'chart-bar-regions',
    name: 'Top Regions',
    description: 'Spend breakdown by geographic cloud region',
    category: 'Charts',
    icon: BarChart2,
    color: '#06B6D4',
    defaultW: 6, defaultH: 5,
    minW: 4, minH: 4,
  },
  {
    id: 'intel-alerts',
    name: 'Active Alerts',
    description: 'Open anomaly detections and budget breach warnings',
    category: 'Intelligence',
    icon: AlertTriangle,
    color: '#F43F5E',
    defaultW: 4, defaultH: 6,
    minW: 3, minH: 4,
  },
  {
    id: 'intel-savings',
    name: 'Top Savings',
    description: 'Highest-impact rightsizing recommendations',
    category: 'Intelligence',
    icon: Zap,
    color: '#10B981',
    defaultW: 4, defaultH: 6,
    minW: 3, minH: 4,
  },
  {
    id: 'intel-budget',
    name: 'Budget Health',
    description: 'Budget utilization status across all accounts',
    category: 'Intelligence',
    icon: Server,
    color: '#06B6D4',
    defaultW: 4, defaultH: 6,
    minW: 3, minH: 4,
  },
]

export const WIDGET_CATEGORIES = ['All', ...new Set(WIDGET_REGISTRY.map(w => w.category))]
